USE [CoursSGBD]

/****** Object:  Table [dbo].[Etudiant]    Script Date: 15/05/2026 14:52:46 ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Etudiant](
	[ETU_id] [int] IDENTITY(1,1) NOT NULL,
	[ETU_NOM] [nvarchar](50) NOT NULL,
	[ETU_PRENOM] [nvarchar](50) NULL,
	[ETU_MATRICULE] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Etudiant] PRIMARY KEY CLUSTERED 
(
	[ETU_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Table [dbo].[KOT]    Script Date: 15/05/2026 14:52:47 ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[KOT](
	[KOT_id] [int] IDENTITY(1,1) NOT NULL,
	[KOT_name] [nvarchar](50) NOT NULL,
	[KOT_ETU_ID] [int] NULL,
 CONSTRAINT [PK_KOT] PRIMARY KEY CLUSTERED 
(
	[KOT_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

